### ISSUE TITLE
missing team_dict.csv file

### ISSUE THREAD

**Issue by rkaimic** [mwfd541/nba#1]
teamfile = pd.read_csv('team_dict.csv')  'team_dist.csv isn't located with the repo, unless I have looked past it.

KeyError: 'OpponentFD' is the result when running buildtest.py

**Comment by mwfd541** [comment]
Right, thanks. I've uploaded the team_dict file.  .

**Comment by rkaimic** [comment]
Thanks for uploading the file everything seems to be working except when i execute xib_fd.py I get this response:

Warning (from warnings module):
  File "/Users//Downloads/nba/xgb_fd.py", line 1
DtypeWarning: Columns (1,42,73) have mixed types. Specify dtype option on import or set low_memory=False.
training data processed
Train xgboost model
Train a XGBoost model
1450

Traceback (most recent call last):
  File "/Users//Downloads/nba/xgb_fd.py", line 63, in <module>
    dtrain = xgb.DMatrix(X_train[features_train], y_train)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost/core.py", line 232, in **init**
    self._init_from_npy2d(data, missing)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost/core.py", line 284, in _init_from_npy2d
    ctypes.byref(self.handle)))
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/xgboost/core.py", line 97, in _check_call
    raise XGBoostError(_LIB.XGBGetLastError())
XGBoostError: There are NAN in the matrix, however, you did not set missing=NAN

any advice with this problem? not sure what the NAN would qualify as. or where to look.
Thanks

**Comment by mwfd541** [comment]
Hmm.  I haven't had any problems - in fact from what I've read about
xgboost it knows how to handle null entries.  I went ahead and added a
couple lines to fillna in this file.

Interestingly, when I use fillna, I get different results - in particular,
a better RMSE : 8.77 goes down to 8.65.

I hope this fixes the problem.  The other possibility is that the somewhere
farther up the data processing stream, some NaN made it in there.
